### ISSUE TITLE
Too many 400 response code for data.flurry.com/v1/flr.do url, after update to 12.1.0 version

### ISSUE THREAD

**Issue by shumidub** [flurry/flurry-android-sdk#14] opened 2020-02-21 12:03 UTC
After update to 12.1.0 version , I found that success rate for request with url data.flurry.com/v1/flr.do (data.flurry.com) is only 85 %. 15 % of all response code is 400 Client error

![изображение](https://user-images.githubusercontent.com/28213564/75032994-e7ede800-54ba-11ea-946e-27ba872f7681.png)

In comparison with other analysts-before that, the difference between analysts was about 5 % on active devices / users. But after the update the difference is about 20 % !!!

**Comment by harman-vz** [comment] 2020-02-21 19:52
Hello, would you be able to give us the name of the app and/or the API key that you're using with 12.1.0 SDK for investigation? Thank you.

**Comment by harman-vz** [comment] 2020-02-21 20:56
Hello, please do provide us with the name of the app and/or API key that is being used with the 12.1.0 SDK for further investigation. You can email us the information to integration@flurry.com, thank you.

**Comment by pai-vz** [comment] 2020-02-24 20:32
Hi @shumidub, we are now investigating this issue and hope to get more info about that. May I ask which version did you use before 12.1.0 and what date did you observe the error rate started to increase significantly?

**Comment by shumidub** [comment] 2020-02-27 15:18
Before we used 11.4.0@aar version, now using - 12.1.0

We updated version to 12.1.0 and uploaded application to Google Play on February 11

And from February 11, we begin to detect poor success rates

**Comment by shumidub** [comment] 2020-03-03 08:40
any update ?

**Comment by pai-vz** [comment] 2020-03-03 20:11
This issue is still investigation. Part of the problem is caused by race condition of IO in SDK and it will be fixed in next SDK release. Others are caused by weird network issue. It seemed that our network request will be interrupted so that BE cannot receive the entire body, which caused the 400 issue. And we are still working on understanding the root reason and whether it will cause data lost or not. 

BTW, did you also observe data lost after upgrade to new version of Flurry? i.e. active user, number of sessions

**Comment by shumidub** [comment] 2020-03-04 06:59
Ok, thanks.
Yeas, I guess some of data lost. 
In comparison with other analysts - with 11.4.0@aar version the difference between other analysts and flurry was about 5 % on active devices / users.
But after the update to 12.1.0 version the difference is about 20 %
But differnence on other analytics between each other (except flurry) was not changed

**Comment by shumidub** [comment] 2020-03-04 07:03
![изображение](https://user-images.githubusercontent.com/28213564/75853394-0d55ec80-5dff-11ea-8668-43701c841f72.png)
![изображение](https://user-images.githubusercontent.com/28213564/75853429-21015300-5dff-11ea-9760-081833dea6bb.png)
![изображение](https://user-images.githubusercontent.com/28213564/75853457-32e2f600-5dff-11ea-813c-45229b8a66ef.png)
![изображение](https://user-images.githubusercontent.com/28213564/75853493-47bf8980-5dff-11ea-839c-772d8e7d9265.png)

**Comment by pai-vz** [comment] 2020-03-11 20:17
Hi @shumidub, after investigation, I think I finally figure out what's going wrong. As I mentioned before, some 400 issues are caused by IO race in SDK, which will cause data lost. It will be fixed in next release. But that only covers small part of the issue. Most of 400 issues are caused by junk data generated by SDK and it will not cause your data lost though you will see many 400 response. We will also address the issue in the next release.

You mentioned that Flurry showed less data than other analytics. But I did see an increase of usage compared to previous version when I checked Flurry backend. So may I ask whether there are still data difference? Has it been better or worse? 

It will be of great help for us to debug if you could share more data with us. If you are OK with that, could you please let me know? For safety, I will ask our support team to reach out to you via email so that we can communicate in private channel.

**Comment by shumidub** [comment] 2020-05-16 14:52
Hello, Could I try 12.3.0 version or should wait next version ?

**Comment by harman-vz** [comment] 2020-05-18 17:52
Hi @shumidub,

The latest SDK release (12.3.0) will improve some of the 400 issues that
are caused by the IO race condition but will not fix the entire issue,
you're welcome to use this version of the SDK for now while we work on the
entirety of the issue which will be fixed in the upcoming version.

Thank you for your patience.

**Closed as completed** 2021-02-05 06:15 UTC
